source 'https://rubygems.org'
gem "selenium-webdriver"
#gem "cucumber"
gem "capybara"
gem "rspec-expectations"
gem "rest-client"
gem "rspec"
gem "pry"
#gem "pry-byebug"
gem "pry-debugger"
#gem 'faker'
